services:
  # Backend API service
  - type: web
    name: gym-tracker-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://gym-tracker-rawhillfish.netlify.app
    healthCheckPath: /health
    autoDeploy: true
    plan: free
