services:
  - type: web
    name: gym-tracker-api
    env: node
    buildCommand: npm install
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://gym-tracker-rawhillfish.netlify.app
      - key: MONGODB_URI
        value: mongodb+srv://jasonnicholaspovey:XrrKaWVfdWuLGTTw@workitout.rjrut.mongodb.net/?retryWrites=true&w=majority&appName=WorkItOut
